# Site settings
title: Stadtpromenade für alle
email: info@stadtpromenade-fuer-alle.de
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://stadtpromenade-fuer-alle.de # the base hostname & protocol for your site

brand: /img/illustrations/sternchen_og.png
navigation:
  - {name: Über uns, link: '/about'}
  - {name: News, link: '/news'}
  #- {name: Chronik, link: '/chronik'}
  - {name: Kontakt, link: '/contact'}

header:
  title: Cottbuser <br> Stadtprome&shy;nade <br> Für Alle!
  subtitle: "Ist das Demokratie, wenn sich ein Spekulant – unter dem Schutz der politischen Machthaber – über den Willen von Zehntausenden Cottbusern hinwegsetzen darf? Setzen wir dem Ausverkauf unserer Stadt ein Ende – holen wir zurück, was uns gehörte! <br><em>Wir fordern: „Stadtpromenade für alle“!</em><br> Wir wollen über die Nutzung des Herzens unserer Stadt mitentscheiden!"

about:
  title: Das traurige Herz von Cottbus
  subtitle: "Es klafft eine offene Wunde in unserer Stadt: Die Brache in der Stadtpromenade. Sie steht symbolisch für die Vernichtung von Hunderttausenden Existenzen auf dem Gebiet der DDR. Der Handlanger des neuen kapitalistischen Systems, die Treuhandanstalt, hat eine ganze Epoche Kultur und Wirtschaft zerstört - mehr als je in einem Krieg vernichtet wurde! Im Gegensatz dazu wurde uns „Demokratie“ versprochen. Ist das Demokratie, wenn sich ein Spekulant – unter dem Schutz der politischen Machthaber – über den Willen von Zehntausenden Cottbusern hinwegsetzen darf? Lassen wir uns nicht länger für dumm verkaufen!"

goal: Unsere Ziele
goals:
  - {title: "Mitbestimmung", subtitle: "Wir wollen die Nutzung von öffentlichem Raum demokratisieren.", glyph: "fa-vote-yea"}
  - {title: "Privatisierung stoppen", subtitle: "Öffentliche Einrichtungen und öffentlicher Raum sollen nicht in privaten Händen sein.", glyph: "fa-users"}

social:
  facebook: {name: Auf Facebook, link: "https://www.facebook.com/Stadtpromenade-f%C3%BCr-Alle-329471711310920/" }
  twitter: ""
  github: {name: Auf Github, link: "https://github.com/Saphareas/cb-stadtprom-fuer-alle" }


# SEO
description: "Wir fordern: „Cottbuser Stadtpromenade für alle“!"
author: Fabian Große
facebook:
  publisher: https://www.facebook.com/Stadtpromenade-f%C3%BCr-Alle-329471711310920/
logo: /img/illustrations/alles_og.png
lang: de_DE

# Analytics
google-analytics: UA-32866583-2

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-admin

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - _posts/_template.md
