# Site settings
title: Stadtpromenade für alle
email: info@stadtpromenade-fuer-alle.de
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://stadtpromenade-fuer-alle.de # the base hostname & protocol for your site

brand: /img/illustrations/sternchen_og.png
navigation:
  - {name: Über uns, link: '/about'}
  - {name: News, link: '/news'}
  #- {name: Chronik, link: '/chronik'}
  - {name: Kontakt, link: '/contact'}

carousel:
  - {color: ccc, title: Erste Slide, subtitle: Lorem ipsum dolor sit amet, consectetur adipiscing elit., active: true}
  - {color: aaa, title: Zweite Slide, subtitle: Praesent commodo cursus magna, vel scelerisque nisl consectetur.}
  - {color: 888, title: Dritte Slide, subtitle: Nulla vitae elit libero, a pharetra augue mollis interdum.}
  - {color: 666, title: Vierte Slide, subtitle: Nulla vitae elit libero, a pharetra augue mollis interdum.}
  - {color: 444, title: Fünfte Slide, subtitle: Nulla vitae elit libero, a pharetra augue mollis interdum.}

social:
  facebook: {name: Auf Facebook, link: "https://www.facebook.com/Stadtpromenade-f%C3%BCr-Alle-329471711310920/" }
  mail: ""
  github: {name: Auf Github, link: "https://github.com/stadtpromenade-fur-alle" }


# SEO
description: "Wir fordern: „Cottbuser Stadtpromenade für alle“!"
author: Fabian Große
facebook:
  publisher: https://www.facebook.com/Stadtpromenade-f%C3%BCr-Alle-329471711310920/
logo: /img/illustrations/alles_og.png
lang: de_DE

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - _posts/_template.md
